### ISSUE TITLE
not working, windows 11 tried with admin rights too

### ISSUE THREAD

**Issue by dannygaray60** [appleforyou/dsvrandom-rv#1]
![Screenshot 2024-12-27 143528](https://github.com/user-attachments/assets/70bb46cd-1489-44d1-ab9c-8b983d9e936a)

**Comment by appleforyou** [comment]
Thanks for the report, it's a little hard to tell what's going on without more info however.
Let me run through some points, just to be thorough:

1. Have you created backup files and if so how did you do it? Clicking the Generate Backup Files button or manually copying the files to your backup folder? For the record, backups aren't optional, especially when your game has mods already.
2. In your backup folder is there a subfolder called "windata"?
3. There should be a file called "alldata_backup.bin" in the windata folder. This is done to mimic the same file structure from the game's folder. Is it not there?

That's what the error message is saying of course, but I should check to be sure we're on the same page. Clicking the randomize button won't work until the backups are settled correctly, so before I ask anything else I have to double-check the basic stuff.

**Comment by dannygaray60** [comment]
1. yeah first tried click on backupdata from the menu but a error message appeared like the attached in this report
2. the only file copied to backup path was "dra03_backup.dll"
3. the file doesn't exists. I tried from zero again, and with backup option started, this is the error msg:
![Screenshot 2024-12-27 221943](https://github.com/user-attachments/assets/4bb431b4-174d-4756-9278-8c9d7c93eeed)

**Comment by dannygaray60** [comment]
and now I copied manually all the original files to backup folder and made "alldata_backup" file from alldata_backup original file, and now the randomizer is working

**Comment by appleforyou** [comment]
Good to hear it's at least working. I'm still curious about the source problem if you're willing to help out, though.

I'd like to test if creating the windata folder is the problem. I'm going to add a new zip file to the latest (v0.3.1) release with _single_folder in the filename. If you can:
1. First unrandomize the game with your existing, working setup
2. Try the single_folder version with an empty backup folder and try to generate backups and run the randomizer.
Could you let me know if this works?
https://github.com/appleforyou/dsvrandom-rv/releases/download/v0.3.1/DSVania_Randomizer_RV-0.3.1_single_folder.zip

I use the subfolder for alldata.bin because it's more convenient for people who use the game folder as their backup folder, but it's possible it's also causing problems for you somehow, based on the fact that one of the files copied properly.

**Comment by dannygaray60** [comment]
it's working! :D

**Comment by appleforyou** [comment]
I think I should be able to implement this into the next version, where if it runs into an error writing alldata.bin it'll try placing it next to dra03.dll, and then do something similar when reading the files. That should cover both approaches.
